modularized code and app fully functioning
bridgetvon/mare-match pull request #6
Opened 2022-10-22 14:52 UTC by bridgetvon

Finally got the stack modularized to help with drawer nav, There is a lot more work to do but at least this makes our app entry much cleaner, working on drawer nav in a new branch

2022-10-22 17:34 UTC, CountDer3k requested changes
Small things to change.

2022-10-22 17:34 UTC, CountDer3k commented on screens/MatchScreen.js
> +import * as React from 'react';
If this file is a component, (or used inside of another screen):
move the file into the screenComponents folder.

2022-10-22 17:34 UTC, CountDer3k commented on package.json
> -    "expo": "~46.0.16",
Add this line back in.

2022-10-22 17:34 UTC, CountDer3k commented on routes/myStack.js
> +    {/* Move this line below so that Login is the first screen before this is merged into main. */}
Remove this comment, it's no longer needed

2022-10-22 17:34 UTC, CountDer3k commented on App.js
> +      <FullStack />
Rename this component to be more descriptive. Possible suggestions:

- ApplicationNavigationStack
- AppNavStack
- RouteNavigationStack

2022-10-22 17:34 UTC, CountDer3k commented on screens/MatchScreen.js
> +    const [checked, setChecked ] = React.useState(false);
Conform to Styling Guide #4.

2022-10-22 17:45 UTC, CountDer3k commented
Update Instructions.txt with all addons you had to install to the project to get the nav bar to work. I saw the json file had new packages in there, so add the commands and links to instructions for how to do that in that file please.

2022-10-22 22:11 UTC, bridgetvon commented on App.js
> +      <FullStack />
this is a temporary component

2022-10-22 22:12 UTC, bridgetvon commented on screens/MatchScreen.js
> +    const [checked, setChecked ] = React.useState(false);
this is a test file for react native paper that I was planning to start but gave up on after once again getting stuck on nav

2022-10-22 22:12 UTC, bridgetvon commented on routes/myStack.js
> +    {/* Move this line below so that Login is the first screen before this is merged into main. */}
will do

2022-10-22 22:12 UTC, bridgetvon commented on package.json
> -    "expo": "~46.0.16",
got it

2022-10-22 22:14 UTC, bridgetvon commented on screens/MatchScreen.js
> +import * as React from 'react';
its just a test, should I delete it? Why are you so short with me? do you hate me????

2022-10-22 22:15 UTC, bridgetvon commented on App.js
> +      <FullStack />
its seperated in another branch, I might make changes to how I'm doing it to get it to work but should be totally different by tomorrow. I'll change it for now tho

2022-10-23 16:10 UTC, CountDer3k commented on screens/MatchScreen.js
> +import * as React from 'react';
Haha you're funny... If it's a tests I would delete it.

2022-10-23 16:12 UTC, CountDer3k commented on screens/MatchScreen.js
> +    const [checked, setChecked ] = React.useState(false);
Ok then we can just remove the paper plugin if you aren't planning on using it.

2022-10-25 22:46 UTC, closed without merging